// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> decryptAesCbcZeroPadding({
  required List<int> data,
  required List<int> key,
  required List<int> iv,
}) => RustLib.instance.api.crateApiCryptoDecryptAesCbcZeroPadding(
  data: data,
  key: key,
  iv: iv,
);
